# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from versiongrid.models.base_model_ import Model
from versiongrid import util


class Component(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, title=None):  # noqa: E501
        """Component - a model defined in OpenAPI

        :param id: The id of this Component.  # noqa: E501
        :type id: str
        :param name: The name of this Component.  # noqa: E501
        :type name: str
        :param title: The title of this Component.  # noqa: E501
        :type title: str
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'title': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'title': 'title'
        }

        self._id = id
        self._name = name
        self._title = title

    @classmethod
    def from_dict(cls, dikt) -> 'Component':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Component of this Component.  # noqa: E501
        :rtype: Component
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Component.


        :return: The id of this Component.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Component.


        :param id: The id of this Component.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Component.


        :return: The name of this Component.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Component.


        :param name: The name of this Component.
        :type name: str
        """

        self._name = name

    @property
    def title(self):
        """Gets the title of this Component.


        :return: The title of this Component.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Component.


        :param title: The title of this Component.
        :type title: str
        """

        self._title = title
