# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from versiongrid.models.base_model_ import Model
from versiongrid.models.dependency_grid_dependencies import DependencyGridDependencies
from versiongrid import util

from versiongrid.models.dependency_grid_dependencies import DependencyGridDependencies  # noqa: E501

class DependencyGrid(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, component=None, version=None, dependencies=None):  # noqa: E501
        """DependencyGrid - a model defined in OpenAPI

        :param component: The component of this DependencyGrid.  # noqa: E501
        :type component: str
        :param version: The version of this DependencyGrid.  # noqa: E501
        :type version: str
        :param dependencies: The dependencies of this DependencyGrid.  # noqa: E501
        :type dependencies: List[DependencyGridDependencies]
        """
        self.openapi_types = {
            'component': str,
            'version': str,
            'dependencies': List[DependencyGridDependencies]
        }

        self.attribute_map = {
            'component': 'component',
            'version': 'version',
            'dependencies': 'dependencies'
        }

        self._component = component
        self._version = version
        self._dependencies = dependencies

    @classmethod
    def from_dict(cls, dikt) -> 'DependencyGrid':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DependencyGrid of this DependencyGrid.  # noqa: E501
        :rtype: DependencyGrid
        """
        return util.deserialize_model(dikt, cls)

    @property
    def component(self):
        """Gets the component of this DependencyGrid.


        :return: The component of this DependencyGrid.
        :rtype: str
        """
        return self._component

    @component.setter
    def component(self, component):
        """Sets the component of this DependencyGrid.


        :param component: The component of this DependencyGrid.
        :type component: str
        """

        self._component = component

    @property
    def version(self):
        """Gets the version of this DependencyGrid.


        :return: The version of this DependencyGrid.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this DependencyGrid.


        :param version: The version of this DependencyGrid.
        :type version: str
        """

        self._version = version

    @property
    def dependencies(self):
        """Gets the dependencies of this DependencyGrid.


        :return: The dependencies of this DependencyGrid.
        :rtype: List[DependencyGridDependencies]
        """
        return self._dependencies

    @dependencies.setter
    def dependencies(self, dependencies):
        """Sets the dependencies of this DependencyGrid.


        :param dependencies: The dependencies of this DependencyGrid.
        :type dependencies: List[DependencyGridDependencies]
        """

        self._dependencies = dependencies
