# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from versiongrid.models.base_model_ import Model
from versiongrid import util


class VersionEnvironments(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, deployed_date=None):  # noqa: E501
        """VersionEnvironments - a model defined in OpenAPI

        :param name: The name of this VersionEnvironments.  # noqa: E501
        :type name: str
        :param deployed_date: The deployed_date of this VersionEnvironments.  # noqa: E501
        :type deployed_date: str
        """
        self.openapi_types = {
            'name': str,
            'deployed_date': str
        }

        self.attribute_map = {
            'name': 'name',
            'deployed_date': 'deployed_date'
        }

        self._name = name
        self._deployed_date = deployed_date

    @classmethod
    def from_dict(cls, dikt) -> 'VersionEnvironments':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Version_environments of this VersionEnvironments.  # noqa: E501
        :rtype: VersionEnvironments
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this VersionEnvironments.


        :return: The name of this VersionEnvironments.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VersionEnvironments.


        :param name: The name of this VersionEnvironments.
        :type name: str
        """

        self._name = name

    @property
    def deployed_date(self):
        """Gets the deployed_date of this VersionEnvironments.


        :return: The deployed_date of this VersionEnvironments.
        :rtype: str
        """
        return self._deployed_date

    @deployed_date.setter
    def deployed_date(self, deployed_date):
        """Sets the deployed_date of this VersionEnvironments.


        :param deployed_date: The deployed_date of this VersionEnvironments.
        :type deployed_date: str
        """

        self._deployed_date = deployed_date
